<?php

namespace Chaostix;

use pocketmine\event\Listener;
use pocketmine\event\player\PlayerLoginEvent;
use pocketmine\plugin\PluginBase;

class Main extends PluginBase implements Listener{

    public $config;
    public function __construct()
    {
        parent::onEnable(); // TODO: Change the autogenerated stub
        $this->getServer()->getPluginManager()->registerEvents($this, $this);
        $this->reloadConfig();
        $this->saveDefaultConfig();

        $this->config = $this->getConfig();
    }

    public function onJoin(PlayerLoginEvent $event)
    {
        $player = $event->getPlayer();
        if(!$player->hasPermission('transfer.bypass') || $this->config->get('wl')[$player->getName()] !== true)
        {
            $player->transfer((string)$this->config->get('ip'), (int)$this->config->get('port'));
        }
    }

}