<?php

namespace Chaostix;

use pocketmine\event\Listener;
use pocketmine\event\player\PlayerLoginEvent;
use pocketmine\plugin\PluginBase;

class Main extends PluginBase implements Listener{

    public $config;
    public function onEnable()
    {
        parent::onEnable(); // TODO: Change the autogenerated stub
        $this->getServer()->getPluginManager()->registerEvents($this, $this);
    }

    public function onJoin(PlayerJoinEvent $event)
    {
        $player = $event->getPlayer();
        if($this->getServer()->hasWhitelist())
        {
            if(!$player->isWhitelisted())
            {
                $player->transfer((string)$this->getConfig('ip'), (int)$this->getConfig('port'));
            }
        }
    }

}
